name: docscanner
description: "An offline Document Scanner."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1




environment:
  sdk: ^3.7.0


dependencies:
  flutter: 
    sdk: flutter
  # functional:
  provider: # NotifierProvider
  fluttertoast: 
  # design:
  dynamic_color: 
  photo_view: 
  # image handling:
  path_provider: 
  image_picker: 
  gal: # save to gallery
  share_plus: # share files
  pdf: 
  file_picker: # select directory to save pdfs to
  # image processing:
  opencv_core: # image processing
  
  #permission_handler: 
  #shared_storage: 
  #saf:
  
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^5.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec


# flutter packages.
flutter:
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  #assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware


  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

