name: docscanner
description: "An offline Document Scanner."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.3.1+20 # Zahl nach + ist "Versionscode", muss jedes Mal erhöht werden




environment:
  sdk: ^3.7.0


dependencies:
  flutter: 
    sdk: flutter
  # functional:
  provider: # NotifierProvider
  fluttertoast: 
  # design:
  dynamic_color: 
  photo_view: 
  # image handling:
  path_provider: 
  path:
  image_picker: 
  gal: # save to gallery
  share_plus: # share files
  pdf: 
  file_selector: # select directory to save pdfs to
  image:
  # image processing:
  opencv_core: # image processing
  # google:
  in_app_purchase:
  flutter_secure_storage: # proUnlocked
  receive_sharing_intent:
    path: lib_plugins/receive_sharing_intent
  camera: 
  camera_android_camerax: 
  camera_platform_interface: 
  google_mobile_ads:
  encrypt:
  shared_preferences:
  permission_handler: 
  url_launcher:
  package_info_plus:
  uuid:
  collection:


dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^5.0.0
  flutter_launcher_icons: 


flutter_launcher_icons:
  android: true
  #ios: true
  image_path: "assets/icon/app_icon_363332_293037_53c5f8_00abf8_282828.png"
  adaptive_icon_background: "#00abf8"
  adaptive_icon_foreground: "assets/icon/app_icon_363332_293037_53c5f8_00abf8_282828.png"
  #dart run flutter_launcher_icons


flutter:
  uses-material-design: true
  
  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/arrow.png

